cursor            #2c2a23
cursor_text_color #e0dcc4

foreground            #2c2a23
background            #D1CDB7
selection_foreground  #1a1a1a
selection_background  #2a6f97
url_color             #2a6f97

#: black 000000 767676
color0  #D1CDB7
color8  #b9b59f
#: red cc0403 f2201f
color1  #b56a6a
color9  #5e2e2e
#: green 19cb00 23fd00
color2  #2a6f97
color10 #003366
#: yellow cecb00 fffd00
color3  #b58f6a
color11 #5e3e2e
#: blue 0d73cc 1a8fff
color4  #6b675a
color12 #2c2a23
#: magenta cb1ed1 fd28ff
color5  #003366
color13 #2a6f97
#: cyan 0dcdcd 14ffff
color6  #6b503a
color14 #b58f6a
#: white dddddd ffffff
color7  #6b675a
color15 #2c2a23

mark1_foreground #2c2a23
mark1_background #f0ecd4
mark2_foreground #ffffff
mark2_background #cce5ff
mark3_foreground #3e2a1a
mark3_background #d4b694

active_tab_foreground #e0dcc4
active_tab_background #2c2a23
inactive_tab_foreground #6b675a
inactive_tab_background #d8d4bc

active_border_color #2c2a23
inactive_border_color #e0dcc4
# bell_border_color #ff5a00
