
bind = ALT, space, exec, qs -p "$HOME/.local/share/Skeleton-Shell" ipc call launcher toggle &
bind = $mainMod, space, exec, qs -p "$HOME/.local/share/Skeleton-Shell" ipc call dashboard toggle &
bind = $mainMod, s, exec, qs -p "$HOME/.local/share/Skeleton-Shell" ipc call settings toggle &
bind = $mainMod, tab, exec, qs -p "$HOME/.local/share/Skeleton-Shell" ipc call overview toggle &
bind = $mainMod, a, exec, qs -p "$HOME/.local/share/Skeleton-Shell" ipc call aiChat toggle &
