$background= rgba(d1cdb7ff)
$error= rgba(b56a6aff)
$error_container= rgba(f5c2c2ff)
$inverse_on_surface= rgba(fcf8e6ff)
$inverse_primary= rgba(f0ecd4ff)
$inverse_surface= rgba(2f312aff)
$on_background= rgba(454138ff)
$on_error= rgba(fff0f0ff)
$on_error_container= rgba(5e2e2eff)
$on_primary= rgba(e0dcc4ff)
$on_primary_container= rgba(6b675aff)
$on_primary_fixed= rgba(2c2a23ff)
$on_primary_fixed_variant= rgba(6b675aff)
$on_secondary= rgba(1a1a1aff)
$on_secondary_container= rgba(003366ff)
$on_secondary_fixed= rgba(ffffffff)
$on_secondary_fixed_variant= rgba(003366ff)
$on_surface= rgba(454138ff)
$on_surface_variant= rgba(6b675aff)
$on_tertiary= rgba(fcf2e6ff)
$on_tertiary_container= rgba(5e3e2eff)
$on_tertiary_fixed= rgba(3e2a1aff)
$on_tertiary_fixed_variant= rgba(6b503aff)
$outline= rgba(9e9a86ff)
$outline_variant= rgba(b7b39fff)
$primary= rgba(454138ff)
$primary_container= rgba(d8d4bcff)
$primary_fixed= rgba(454138ff)
$primary_fixed_dim= rgba(6b675aff)
$scrim= rgba(000000ff)
$secondary= rgba(2a6f97ff)
$secondary_container= rgba(b3d9ffff)
$secondary_fixed= rgba(cce5ffff)
$secondary_fixed_dim= rgba(99c2ffff)
$shadow= rgba(141414ff)
$source_color= rgba(2a6f97ff)
$surface= rgba(D1CDB7ff)
$surface_bright= rgba(f0ecd4ff)
$surface_container= rgba(DCD8C0ff)
$surface_container_high= rgba(ccc8b1ff)
$surface_container_highest= rgba(b9b59fff)
$surface_container_low= rgba(f5f1dbff)
$surface_container_lowest= rgba(fcf8e1ff)
$surface_dim= rgba(c2bea6ff)
$surface_tint= rgba(a7a38dff)
$surface_variant= rgba(aca890ff)
$tertiary= rgba(b58f6aff)
$tertiary_container= rgba(f0d9c2ff)
$tertiary_fixed= rgba(d4b694ff)
$tertiary_fixed_dim= rgba(946f4aff)
$error= rgba(b56a6aff)
$error_container= rgba(f5c2c2ff)
$inverse_on_surface= rgba(fcf8e6ff)
$inverse_primary= rgba(f0ecd4ff)
$inverse_surface= rgba(2f312aff)
$on_background= rgba(454138ff)
$on_error= rgba(fff0f0ff)
$on_error_container= rgba(5e2e2eff)
$on_primary= rgba(e0dcc4ff)
$on_primary_container= rgba(6b675aff)
$on_primary_fixed= rgba(2c2a23ff)
$on_primary_fixed_variant= rgba(6b675aff)
$on_secondary= rgba(1a1a1aff)
$on_secondary_container= rgba(003366ff)
$on_secondary_fixed= rgba(ffffffff)
$on_secondary_fixed_variant= rgba(003366ff)
$on_surface= rgba(454138ff)
$on_surface_variant= rgba(6b675aff)
$on_tertiary= rgba(fcf2e6ff)
$on_tertiary_container= rgba(5e3e2eff)
$on_tertiary_fixed= rgba(3e2a1aff)
$on_tertiary_fixed_variant= rgba(6b503aff)
$outline= rgba(9e9a86ff)
$outline_variant= rgba(b7b39fff)
$primary= rgba(454138ff)
$primary_container= rgba(d8d4bcff)
$primary_fixed= rgba(454138ff)
$primary_fixed_dim= rgba(6b675aff)
$scrim= rgba(000000ff)
$secondary= rgba(2a6f97ff)
$secondary_container= rgba(b3d9ffff)
$secondary_fixed= rgba(cce5ffff)
$secondary_fixed_dim= rgba(99c2ffff)
$shadow= rgba(141414ff)
$source_color= rgba(2a6f97ff)
$surface= rgba(D1CDB7ff)
$surface_bright= rgba(f0ecd4ff)
$surface_container= rgba(DCD8C0ff)
$surface_container_high= rgba(ccc8b1ff)
$surface_container_highest= rgba(b9b59fff)
$surface_container_low= rgba(f5f1dbff)
$surface_container_lowest= rgba(fcf8e1ff)
$surface_dim= rgba(c2bea6ff)
$surface_tint= rgba(a7a38dff)
$surface_variant= rgba(aca890ff)
$tertiary= rgba(b58f6aff)
$tertiary_container= rgba(f0d9c2ff)
$tertiary_fixed= rgba(d4b694ff)
$tertiary_fixed_dim= rgba(946f4aff)
